Add a WebSocket layer to the Server
MusalaSoft/atmosphere-server pull request #5
Opened 2017-05-09 15:45 UTC by dim4o

Update the Agent's database scheme
Add a WebSocket layer to the Server 
Apply the WebSocket layer to the project
Fix Server's tests

2017-05-10 11:17 UTC, Perseverance requested changes

2017-05-10 11:17 UTC, Perseverance commented on src/main/java/com/musala/atmosphere/server/websocket/ServerWebsocketDispatcher.java
> +    public void sendPing(String agentId) throws IllegalStateException, IOException {
Rename this to sendPong and add method sendPing that sends Ping

2017-05-10 11:36 UTC, Perseverance requested changes

2017-05-10 11:36 UTC, Perseverance commented on src/main/java/com/musala/atmosphere/server/Server.java
> +    private ServerWebsocketDispatcher despatcher = ServerWebsocketDispatcher.getInstance();
Dispatcher instead of despatcher

2017-05-10 11:36 UTC, Perseverance commented on src/main/java/com/musala/atmosphere/server/Server.java
>          serverRmiPort = serverPort;
I don't think the RMI thing is correct

2017-05-10 11:36 UTC, Perseverance commented on src/main/java/com/musala/atmosphere/server/ServerManager.java
>       *        - the unique RMI identifier of the device
Please fix the RMI javadocs in the whole class

2017-05-10 11:36 UTC, Perseverance commented on src/main/java/com/musala/atmosphere/server/monitor/AgentMonitor.java
>      public void inform(AgentConnectedEvent event) {
Let's put the logic for connect before the logic for disconnect

2017-05-11 10:26 UTC, dim4o commented on src/main/java/com/musala/atmosphere/server/websocket/ServerWebsocketDispatcher.java
> +    public void sendPing(String agentId) throws IllegalStateException, IOException {
done

2017-05-11 10:27 UTC, dim4o commented on src/main/java/com/musala/atmosphere/server/Server.java
> +    private ServerWebsocketDispatcher despatcher = ServerWebsocketDispatcher.getInstance();
done

2017-05-11 10:27 UTC, dim4o commented on src/main/java/com/musala/atmosphere/server/Server.java
>          serverRmiPort = serverPort;
done

2017-05-11 10:28 UTC, dim4o commented on src/main/java/com/musala/atmosphere/server/monitor/AgentMonitor.java
>      public void inform(AgentConnectedEvent event) {
done

2017-05-12 14:15 UTC, dim4o commented on src/main/java/com/musala/atmosphere/server/ServerManager.java
>       *        - the unique RMI identifier of the device
done

2017-05-15 07:51 UTC, Perseverance approved these changes

2017-05-30 16:16 UTC, bstrandjev approved these changes

2017-05-31 07:49 UTC, bstrandjev approved these changes

2017-05-31 07:49 UTC, bstrandjev commented on src/main/java/com/musala/atmosphere/server/websocket/ServerDispatcher.java
> +            ex.printStackTrace();
be consistent to your approach to exceptions - sometimes you print stack trace, sometimes you use LOGGER. I believe the latter is better

2017-05-31 07:49 UTC, bstrandjev commented on src/main/java/com/musala/atmosphere/server/websocket/ServerDispatcher.java
> +    void sendToClient(String json) {
please verify this really needs to be package protected, not private

2017-05-31 07:49 UTC, bstrandjev commented on src/main/java/com/musala/atmosphere/server/websocket/ServerDispatcher.java
> +    void sendGetDeviceAllocationInfoRequest(RequestMessage getDeviceAllocationInformationRequest,
verify package protected

2017-05-31 07:49 UTC, bstrandjev commented on src/main/java/com/musala/atmosphere/server/websocket/ServerDispatcher.java
> +     * @param deviceSelector
this java doc is not for this method

2017-05-31 07:49 UTC, bstrandjev commented on src/main/java/com/musala/atmosphere/server/websocket/ServerAgentEndpoint.java
> +        // LOGGER.debug("Server: onMessage called");
please either remove or uncomment

2017-05-31 08:14 UTC, bstrandjev reviewed
I think github might have got a bit troubled with the size of your changes - please note that there should be about 4 comments on this commit

2017-05-31 08:14 UTC, bstrandjev commented on src/main/java/com/musala/atmosphere/server/pool/PoolManager.java
> +    private static final String DEVICE_ID_FORMAT = "%s_%s";
aha, here is the format - you can reuse this in the previous file i commented on

2017-05-31 08:14 UTC, bstrandjev commented on src/main/java/com/musala/atmosphere/server/pool/PoolManager.java
> +        for (int index = 0; index < availableDevicesList.size(); index++) {
Prefer enhanced for loops

2017-05-31 08:16 UTC, bstrandjev approved these changes
I love your concept of "Fix tests"

2017-05-31 14:33 UTC, dim4o commented on src/main/java/com/musala/atmosphere/server/websocket/ServerDispatcher.java
> +            ex.printStackTrace();
Done.

2017-05-31 14:34 UTC, dim4o commented on src/main/java/com/musala/atmosphere/server/websocket/ServerDispatcher.java
> +    void sendToClient(String json) {
Called from another class in the same package: `ServerAgentEndpoint`.

2017-05-31 14:34 UTC, dim4o commented on src/main/java/com/musala/atmosphere/server/websocket/ServerDispatcher.java
> +     * @param deviceSelector
Done.

2017-05-31 14:34 UTC, dim4o commented on src/main/java/com/musala/atmosphere/server/websocket/ServerDispatcher.java
> +    void sendGetDeviceAllocationInfoRequest(RequestMessage getDeviceAllocationInformationRequest,
Called from another class in the same package: `ClientServerEndpoint`.

2017-05-31 14:34 UTC, dim4o commented on src/main/java/com/musala/atmosphere/server/websocket/ServerAgentEndpoint.java
> +        // LOGGER.debug("Server: onMessage called");
Removed.

2017-05-31 14:35 UTC, dim4o commented on src/main/java/com/musala/atmosphere/server/pool/PoolManager.java
> +        for (int index = 0; index < availableDevicesList.size(); index++) {
Done.

2017-05-31 14:35 UTC, dim4o commented on src/main/java/com/musala/atmosphere/server/pool/PoolManager.java
> +    private static final String DEVICE_ID_FORMAT = "%s_%s";
I didn't find this comment but I think I understood this remark. `buildDeviceIdentifier(...)` can be used statically: `Poolmanager.buildDeviceIdentifier(..)` and I don't need of something like `DEVICE_ID_FORMATTER` in the `ServerManager`.

2017-07-27 15:20 UTC, merged